// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function Disconnect(arg1) {
  return window['go']['main']['App']['Disconnect'](arg1);
}

export function DiscoverDevices() {
  return window['go']['main']['App']['DiscoverDevices']();
}

export function GetIdentity() {
  return window['go']['main']['App']['GetIdentity']();
}

export function GetNTPSettings() {
  return window['go']['main']['App']['GetNTPSettings']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function ListAuthorizedDevices() {
  return window['go']['main']['App']['ListAuthorizedDevices']();
}

export function RemoveAuthorizedDevice(arg1) {
  return window['go']['main']['App']['RemoveAuthorizedDevice'](arg1);
}

export function RespondConnection(arg1, arg2, arg3) {
  return window['go']['main']['App']['RespondConnection'](arg1, arg2, arg3);
}

export function SaveLocalSettings(arg1, arg2) {
  return window['go']['main']['App']['SaveLocalSettings'](arg1, arg2);
}

export function SaveNTPServer(arg1) {
  return window['go']['main']['App']['SaveNTPServer'](arg1);
}

export function TestNTPServer() {
  return window['go']['main']['App']['TestNTPServer']();
}
