// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {config} from '../models';

export function Connect(arg1:main.Device):Promise<void>;

export function Disconnect(arg1:string):Promise<void>;

export function DiscoverDevices():Promise<Array<main.Device>>;

export function GetIdentity():Promise<main.Identity>;

export function GetStatus():Promise<main.Status>;

export function ListAuthorizedDevices():Promise<Array<config.AuthorizedDevice>>;

export function RemoveAuthorizedDevice(arg1:string):Promise<void>;

export function RespondConnection(arg1:string,arg2:boolean,arg3:boolean):Promise<void>;

export function SaveLocalSettings(arg1:number,arg2:number):Promise<void>;
