// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Connect(arg1:main.Device):Promise<void>;

export function Disconnect():Promise<void>;

export function DiscoverDevices():Promise<Array<main.Device>>;

export function GetStatus():Promise<main.Status>;
