// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function DiscoverDevices() {
  return window['go']['main']['App']['DiscoverDevices']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}
