<script setup lang="ts">
import { onMounted, ref } from 'vue';
// Wails writes these bridge modules during `wails dev` and `wails build`.
import { DiscoverDevices, Connect, Disconnect, GetStatus } from '../wailsjs/go/main/App';
import { EventsOn } from '../wailsjs/runtime/runtime';
type Device={name:string;host:string;port:number;id:string}; const devices=ref<Device[]>([]); const status=ref('已断开连接'); const active=ref<Device|null>(null);
const normalizeDevice=(raw:any):Device=>({name:raw?.name??raw?.Name??'Android device',host:raw?.host??raw?.Host??'',port:raw?.port??raw?.Port??0,id:raw?.id??raw?.ID??raw?.Id??raw?.name??raw?.Name??''});
const discover=async()=>{devices.value=[];try{await DiscoverDevices()}catch{status.value='发现设备失败'}}; const connect=async(d:Device)=>{try{await Connect({Name:d.name,Host:d.host,Port:d.port,ID:d.id});active.value=d;status.value='正在传输系统音频'}catch{active.value=null;status.value='连接或启动音频采集失败'}}; const disconnect=async()=>{try{await Disconnect();active.value=null;status.value='已断开连接'}catch{status.value='断开连接失败'}};
onMounted(async()=>{try{const s:any=await GetStatus();status.value=(s?.message??s?.Message??'已断开连接')}catch{status.value='无法获取连接状态'} EventsOn('device:found',(raw:any)=>{const d=normalizeDevice(raw);if(!devices.value.some(x=>x.id===d.id))devices.value.push(d)});EventsOn('stream:status',(raw:any)=>{status.value=raw?.message??raw?.Message??'状态未知'});discover()});
</script>
<template><main><header><div><p class="eyebrow">本地音频</p><h1>SteamVoice</h1></div><span :class="['status',active?'live':'']">{{status}}</span></header><section><div class="section-head"><div><h2>你的 Android 扬声器</h2><p>当前 Wi-Fi 网络中正在广播的设备</p></div><button @click="discover">刷新</button></div><div v-if="devices.length" class="devices"><article v-for="d in devices" :key="d.id"><div class="speaker">S</div><div><h3>{{d.name}}</h3><p>{{d.host}}:{{d.port}}</p></div><button v-if="active?.id===d.id" class="secondary" @click="disconnect">断开连接</button><button v-else @click="connect(d)">连接</button></article></div><div v-else class="empty">正在本地网络中查找 SteamVoice 接收端...</div></section><footer>48 kHz · 立体声 PCM · UDP · 系统音频采集</footer></main></template>
<style> :root{font-family:Inter,system-ui,sans-serif;color:#172033;background:#f6f7f8}body{margin:0}main{max-width:940px;margin:auto;padding:44px 32px}header,.section-head,article{display:flex;align-items:center;justify-content:space-between;gap:18px}header{border-bottom:1px solid #d9dde1;padding-bottom:29px}.eyebrow{color:#687077;font-size:12px;font-weight:700;margin:0 0 5px}h1{font-size:32px;margin:0}h2{margin:0;font-size:21px}h3{margin:0 0 5px}p{color:#687077;margin:0}.status{font-size:14px;padding:8px 12px;border:1px solid #d9dde1;background:#fff}.status.live{border-color:#16805b;color:#086d4d}section{margin-top:42px}.section-head{margin-bottom:16px}button{border:0;background:#086d4d;color:#fff;padding:10px 15px;font-weight:650;cursor:pointer}.secondary{background:#e8ecee;color:#172033}.devices{border-top:1px solid #d9dde1}article{background:#fff;border-bottom:1px solid #d9dde1;padding:18px}.speaker{width:34px;height:34px;display:grid;place-items:center;background:#f0c75e;font-weight:800;margin-right:0}article>div:nth-child(2){flex:1}.empty{border:1px dashed #b8c0c6;padding:32px;color:#687077}footer{margin-top:44px;color:#687077;font-size:13px}@media(max-width:600px){main{padding:26px 18px}header{align-items:flex-start}.section-head,article{align-items:flex-start;flex-wrap:wrap}}</style>
